<?php
/**
 * @license MIT. Please see the LICENSE file for more info.
 * @author Phuong LE <sony@menincode.com>
 * @copyright Copyright (c) 2019 Men In Code Ltd (http://www.menincode.com)
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Easygento\InstanceReminder\Helper\Config */
$helper = $this->helper('\Easygento\InstanceReminder\Helper\Config')
?>

<?php if ($helper->isEnabled()) : ?>
    <div id="easygento_ribbon" style="background-color: <?php echo $helper->getColorByInstance() ?>">
        <div class="logo">
            <span><?php echo $helper->getInstanceName() ?></span>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "#easygento_ribbon": {
                "Easygento_InstanceReminder/js/ribbon" : {}
            }
        }

    </script>
<?php endif; ?>

