<?php
/**
 * Easygento
 * @author Phuong LE <web.phuong.le@gmail.com>
 * @license Open Source License
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Easygento\InstanceReminder\Helper\Config */
$helper = $this->helper('\Easygento\InstanceReminder\Helper\Config')
?>

<?php if ($helper->isEnabled()) : ?>
    <div id="easygento_ribbon" style="background-color: <?php echo $helper->getColorByInstance() ?>">
        <div class="logo">
            <span style="color: <?php echo $helper->getLabelColor() ?> "><?php echo $helper->getInstanceName() ?></span>
        </div>
    </div>

    <script type="text/x-magento-init">
        {
            "#easygento_ribbon": {
                "Easygento_InstanceReminder/js/ribbon" : {}
            }
        }

    </script>
<?php endif; ?>

